apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: amt-tiltaksarrangor-bff-alerts
  namespace: amt
  labels:
    team: amt
spec:
  groups:
    - name: amt-tiltaksarrangor-bff-alerts
      rules:
        - alert: applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="amt-tiltaksarrangor-bff"} == 0
          for: 2m
          annotations:
            summary: "App {{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
            action: "`kubectl describe pod -l app={{ $labels.deployment}}` -> `kubectl logs -l app={{ $labels.deployment}}`"
          labels:
            namespace: amt
            severity: critical
        - alert: høy feilrate i logger
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="amt-tiltaksarrangor-bff",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="amt-tiltaksarrangor-bff"}[3m]))) > 10
          for: 3m
          annotations:
            action: "Sjekk loggene til app amt-tiltaksarrangor-bff i namespace amt, for å se hvorfor det er så mye feil"
          labels:
            namespace: amt
            severity: warning
        - alert: feil logges
          expr: sum by(log_app, log_namespace) (increase(logd_messages_total{log_app="amt-tiltaksarrangor-bff",log_level=~"Error"}[5m])) > 0
          for: 5m
          annotations:
            action: "Sjekk loggene til app amt-tiltaksarrangor-bff i namespace amt, for å se hva som feiler"
          labels:
            namespace: amt
            severity: warning