kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-tiltaksarrangor-bff-temp
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  gcp:
    sqlInstances:
      - name: amt-tiltaksarrangor-bff-2
        type: POSTGRES_17
        tier: db-custom-1-3840
        databases:
          - name: amt-tiltaksarrangor-bff
            envVarPrefix: DB
        diskAutoresize: false
        highAvailability: false
        insights:
          enabled: true
  port: 8080
  ingresses:
    - https://amt-tiltaksarrangor-bff-temp.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 60
  liveness:
    path: /internal/health/liveness
    initialDelay: 60
    timeout: 3
  replicas:
    min: 0
    max: 0
    scalingStrategy:
      cpu:
        thresholdPercentage: 200
  resources:
    requests:
      cpu: 50m
      memory: 700Mi
    limits:
      memory: 2048Mi
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltaksarrangor-flate
    outbound:
      rules:
        - application: amt-tiltak
        - application: amt-arrangor
        - application: amt-person-service
        - application: amt-deltaker
      external:
        - host: amt-unleash-api.nav.cloud.nais.io
  leaderElection: true
  envFrom:
    - secret: amt-tiltaksarrangor-bff-unleash-api-token
  env:
    - name: AMT_TILTAK_TOKENX_CLIENT_ID
      value: prod-gcp:amt:amt-tiltak
    - name: AMT_ARRANGOR_TOKENX_CLIENT_ID
      value: prod-gcp:amt:amt-arrangor
    - name: AMT_ARRANGOR_AAD_CLIENT_ID
      value: api://prod-gcp.amt.amt-arrangor/.default
    - name: AMT_PERSON_AAD_CLIENT_ID
      value: api://prod-gcp.amt.amt-person-service/.default
    - name: AMT_DELTAKER_AAD_CLIENT_ID
      value: api://prod-gcp.amt.amt-deltaker/.default

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki