kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-tiltaksarrangor-bff
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  gcp:
    sqlInstances:
      - name: amt-tiltaksarrangor-bff
        type: POSTGRES_14
        databases:
          - name: amt-tiltaksarrangor-bff
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        insights:
          enabled: true
  port: 8080
  ingresses:
    - https://amt-tiltaksarrangor-bff.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  startup:
    path: /internal/health/liveness
    initialDelay: 10
    failureThreshold: 30
    periodSeconds: 5
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 512Mi
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltaksarrangor-flate
    outbound:
      rules:
        - application: amt-tiltak
        - application: amt-arrangor
  leaderElection: true
  env:
    - name: AMT_TILTAK_TOKENX_CLIENT_ID
      value: dev-gcp:amt:amt-tiltak
    - name: AMT_ARRANGOR_TOKENX_CLIENT_ID
      value: dev-gcp:amt:amt-arrangor