ALTER TABLE deltakerliste RENAME COLUMN tiltak_navn TO tiltaksnavn;
ALTER TABLE deltakerliste ADD COLUMN tiltakskode varchar;

UPDATE deltakerliste SET tiltakskode = CASE tiltak_type
   WHEN 'ARBFORB' THEN 'ARBEIDSFORBEREDENDE_TRENING'
   WHEN 'ARBRRHDAG' THEN 'ARBEIDSRETTET_REHABILITERING'
   WHEN 'AVKLARAG' THEN 'AVKLARING'
   WHEN 'DIGIOPPARB' THEN 'DIGITALT_OPPFOLGINGSTILTAK'
   WHEN 'GRUPPEAMO' THEN 'GRUPPE_ARBEIDSMARKEDSOPPLAERING'
   WHEN 'GRUFAGYRKE' THEN 'GRUPPE_FAG_OG_YRKESOPPLAERING'
   WHEN 'INDOPPFAG' THEN 'OPPFOLGING'
   WHEN 'VASV' THEN 'VARIG_TILRETTELAGT_ARBEID_SKJERMET'
   WHEN 'JOBBK' THEN 'JOBBKLUBB'
END;

ALTER TABLE deltakerliste ALTER COLUMN tiltakskode SET NOT NULL;
ALTER TABLE deltakerliste DROP COLUMN tiltak_type;
